[profile.release]
strip = true
opt-level = "z"
panic = "abort"

[package]
name = "sslex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.45"
rand = "0.8.5"
hex = "0.4.3"
clap = { version = "4.1.8" }
